### ISSUE TITLE
Add show_restricted and click_insert functionality

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/fast_token_browser#22]
In the issue advocating the incorporation of this module in core, it was suggested that the show_restricted and click_insert functionality be added to this module.

https://github.com/backdrop/backdrop-issues/issues/6143

**Comment by argiepiano** [comment]
PR is WIP. I discovered an issue with show_restricted and the token cache that this module uses. See main core issue for details.

**Comment by argiepiano** [comment]
OK, this cache problem has been fixed. To test, see directions [here](https://github.com/backdrop/backdrop-issues/issues/6143#issuecomment-2415689675)

**Comment by herbdool** [comment]
I was just adding a field to an existing View and got this warning:

> Warning: Undefined array key "show_restricted" in theme_fast_token_browser_link() (line 15 of /app/httpdocs/modules/contrib/fast_token_browser/fast_token_browser.theme.inc).
> Warning: Undefined array key "show_restricted" in theme_fast_token_browser_link() (line 36 of /app/httpdocs/modules/contrib/fast_token_browser/fast_token_browser.theme.inc).
Warning: Undefined array key "click_insert" in theme_fast_token_browser_link() (line 37 of /app/httpdocs/modules/contrib/fast_token_browser/fast_token_browser.theme.inc).

But then I cleared the cache and redid it. No warning the second time. So I'm going to reclose this.
